"use client"

import { useState } from 'react'
import { DeliveryRequestForm } from '../DeliveryRequest'

const responsibilities = [
  ['01', 'Подбор транспорта и перевозчика', 'Подбираем вариант под маршрут, параметры груза и условия конкретной перевозки.'],
  ['02', 'Проверка перед рейсом', 'Проверяем перевозчика, водителя и транспорт до того, как груз выйдет в путь.'],
  ['03', 'Сопровождение', 'Остаёмся на связи в течение рейса и контролируем ключевые этапы перевозки.'],
  ['04', 'Документы', 'Сопровождаем документооборот, работаем с ЭДО и электронными перевозочными документами.'],
]
const startSteps = [['Задача', 'Маршрут, груз, сроки и особенности перевозки.'], ['Условия', 'Уточняем требования и согласовываем рабочую схему.'], ['Перевозчик', 'Подбираем и проверяем подходящего исполнителя.'], ['Рейс', 'Организуем перевозку и сопровождаем её до завершения.']]
const facts = [['С 2008 года', 'работаем в перевозках'], ['от 8 млн ₽', 'страхование ответственности на рейс'], ['Проверка перевозчиков', 'до допуска к перевозке'], ['ЭДО и ЭТрН', 'работаем с электронным документооборотом']]
const faq = [['Как производится оплата?', 'Работаем по безналичному расчёту. Конкретные условия оплаты согласовываются при начале работы.'], ['Возможна ли отсрочка платежа?', 'Условия оплаты и возможная отсрочка обсуждаются индивидуально с учётом объёма и характера работы.'], ['Предоставляете ли скидки?', 'Стоимость зависит от маршрута, типа транспорта, регулярности перевозок и других условий. Для постоянной работы условия согласовываются отдельно.'], ['Как застрахована ответственность?', 'Ответственность Вир-Транс страхуется. Базовый ориентир страхового покрытия на рейс — от 8 млн ₽; при необходимости условия уточняются под конкретную перевозку.'], ['Работаете ли по ЭДО и ЭТрН?', 'Да. Работаем с электронным документооборотом и электронными перевозочными документами.'], ['Какие документы предоставляете?', 'Комплект документов зависит от перевозки и условий клиента. Необходимый порядок согласовываем до начала работы.']]

function ProcessDiagram() {
  const nodes = ['Задача', 'Проверка', 'Перевозка', 'Документы']
  return <div className="relative mx-auto w-full min-w-0 max-w-full border border-brand-border bg-brand-surface p-5 sm:max-w-[36rem] sm:p-7 xl:max-w-none" aria-label="Схема процесса работы">
    <div className="absolute left-5 top-5 h-2 w-2 bg-brand-accent sm:left-7 sm:top-7" /><p className="ml-5 text-xs font-extrabold tracking-[0.12em] text-brand-secondary sm:ml-6">РАБОЧАЯ СХЕМА</p>
    <div className="relative mt-7 grid min-w-0 grid-cols-2 gap-x-6 gap-y-5 sm:mt-9 sm:gap-x-9 sm:gap-y-7">
      <span className="pointer-events-none absolute left-1/4 right-1/4 top-[2.3rem] border-t border-brand-accent sm:top-[2.65rem]" />
      <span className="pointer-events-none absolute bottom-[2.3rem] top-[2.3rem] left-3/4 border-l border-brand-accent sm:bottom-[2.65rem] sm:top-[2.65rem]" />
      <span className="pointer-events-none absolute bottom-[2.3rem] left-1/4 right-1/4 border-t border-brand-accent sm:bottom-[2.65rem]" />
      <span className="pointer-events-none absolute left-1/2 top-[2.3rem] h-1.5 w-1.5 -translate-x-1/2 -translate-y-1/2 rotate-45 border-r border-t border-brand-accent sm:top-[2.65rem]" />
      <span className="pointer-events-none absolute left-3/4 top-1/2 h-1.5 w-1.5 -translate-x-1/2 -translate-y-1/2 rotate-45 border-b border-r border-brand-accent" />
      <span className="pointer-events-none absolute bottom-[2.3rem] left-1/2 h-1.5 w-1.5 -translate-x-1/2 -translate-y-1/2 rotate-45 border-b border-l border-brand-accent sm:bottom-[2.65rem]" />
      {nodes.map((node, index) => <div key={node} className={`relative min-w-0 bg-brand-surface ${index === 2 ? 'col-start-2 row-start-2' : ''}`}><div className="border border-brand-primary px-2 py-3 text-center text-sm font-bold tracking-[-0.04em] text-brand-primary sm:px-3 sm:py-4 sm:text-base"><span className="mb-1 block text-[10px] font-extrabold tracking-[0.12em] text-brand-accent">0{index + 1}</span>{node}</div></div>)}
    </div>
    <p className="mt-6 border-t border-brand-border pt-4 text-sm leading-6 text-[var(--color-text-secondary-content)]">Один ответственный контакт ведёт задачу от вводных до документов.</p>
  </div>
}

export default function ForClients() {
  const [openFaq, setOpenFaq] = useState<number | null>(0)
  return <main>
    <section className="bg-brand-background" aria-labelledby="clients-title"><div className="content-container grid min-w-0 grid-cols-1 gap-12 py-16 sm:py-20 xl:grid-cols-[minmax(0,1.25fr)_minmax(22rem,0.75fr)] xl:items-center xl:gap-14 xl:py-28"><div className="min-w-0 w-full max-w-3xl"><p className="text-xs font-extrabold tracking-[0.12em] text-brand-accent">КЛИЕНТАМ</p><h1 id="clients-title" className="mt-4 max-w-full text-[2.2rem] font-extrabold leading-[0.92] tracking-[-0.065em] text-brand-primary sm:text-[clamp(3.6rem,8vw,4.5rem)] xl:text-[clamp(3.9rem,5vw,4.6rem)]">Перевозки без лишней неопределённости</h1><p className="mt-7 max-w-xl text-lg leading-[1.5] text-[var(--color-text-secondary-content)] sm:text-xl">Берём на себя подбор перевозчика, проверку, сопровождение рейса и работу с документами.</p><a href="#client-contact" className="mt-9 inline-flex min-h-14 items-center justify-center rounded-[var(--radius-sm)] bg-brand-accent px-7 text-base font-semibold text-white transition-colors hover:bg-[var(--color-accent-orange-hover)] sm:px-8 sm:text-lg">Обсудить задачу</a></div><div className="min-w-0 w-full max-w-full"><ProcessDiagram /></div></div></section>
    <section id="responsibilities" className="bg-brand-graphite text-white" aria-labelledby="responsibilities-title"><div className="content-container section-spacing"><div className="max-w-2xl"><p className="text-xs font-extrabold tracking-[0.12em] text-brand-accent">ПРОЦЕСС РАБОТЫ</p><h2 id="responsibilities-title" className="mt-4 text-[clamp(2.3rem,4.8vw,4.8rem)] font-extrabold leading-[0.96] tracking-[-0.06em]">Что мы берём на себя</h2></div><div className="mt-14 border-t border-white/20">{responsibilities.map(([number, title, text]) => <article key={number} className="grid gap-4 border-b border-white/20 py-7 sm:grid-cols-[4rem_minmax(12rem,0.78fr)_minmax(0,1.22fr)] sm:gap-8 sm:py-9"><p className="text-xs font-extrabold tracking-[0.12em] text-brand-accent">{number}</p><h3 className="text-xl font-bold tracking-[-0.04em] sm:text-2xl">{title}</h3><p className="max-w-xl text-base leading-7 text-[var(--color-text-secondary-on-graphite)] sm:text-lg sm:leading-relaxed">{text}</p></article>)}</div></div></section>
    <section id="start" className="bg-brand-surface" aria-labelledby="start-title"><div className="content-container section-spacing grid gap-12 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)] lg:gap-20"><div className="max-w-xl"><p className="text-xs font-extrabold tracking-[0.12em] text-brand-secondary">НАЧАЛО РАБОТЫ</p><h2 id="start-title" className="mt-4 text-[clamp(2.3rem,4.4vw,4.25rem)] font-extrabold leading-[0.96] tracking-[-0.06em] text-brand-primary">Для старта достаточно нескольких вводных</h2></div><ol className="border-t border-brand-border">{startSteps.map(([title, text], index) => <li key={title} className="grid gap-2 border-b border-brand-border py-5 sm:grid-cols-[3.5rem_10rem_1fr] sm:items-baseline sm:gap-5 sm:py-6"><span className="text-xs font-extrabold tracking-[0.12em] text-brand-accent">0{index + 1}</span><span className="text-xl font-bold tracking-[-0.04em] text-brand-primary sm:text-2xl">{title}</span><span className="text-base leading-7 text-[var(--color-text-secondary-content)]">{text}</span></li>)}</ol></div></section>
    <section className="bg-[#eee9e1]" aria-labelledby="facts-title"><div className="content-container section-spacing"><div className="flex flex-col gap-5 border-t-2 border-brand-accent pt-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-extrabold tracking-[0.12em] text-brand-secondary">ОСНОВАНИЯ ДЛЯ ДОВЕРИЯ</p><h2 id="facts-title" className="mt-4 max-w-2xl text-[clamp(2.3rem,4.4vw,4.25rem)] font-extrabold leading-[0.96] tracking-[-0.06em] text-brand-primary">В работе важны проверяемые вещи</h2></div><p className="max-w-sm text-base leading-7 text-[var(--color-text-secondary-content)]">Страхование ответственности: Росгосстрах, Ингосстрах, Согласие, ПАРИ.</p></div><div className="mt-12 grid border-t border-brand-border sm:grid-cols-2 lg:grid-cols-4">{facts.map(([value, label], index) => <article key={value} className={`border-b border-brand-border py-7 sm:px-7 lg:border-b-0 lg:py-1 ${index < 3 ? 'lg:border-r' : ''} ${index % 2 === 0 ? 'sm:pl-0' : ''} ${index === 3 ? 'lg:pr-0' : ''}`}><p className="text-2xl font-extrabold tracking-[-0.05em] text-brand-primary sm:text-3xl">{value}</p><p className="mt-3 max-w-[13rem] text-base leading-6 text-[var(--color-text-secondary-content)]">{label}</p></article>)}</div></div></section>
    <section id="questions" className="bg-brand-background" aria-labelledby="faq-title"><div className="content-container section-spacing grid gap-12 lg:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)] lg:gap-20"><div className="max-w-xl"><p className="text-xs font-extrabold tracking-[0.12em] text-brand-accent">РАБОЧИЕ ВОПРОСЫ</p><h2 id="faq-title" className="mt-4 text-[clamp(2.3rem,4.2vw,4.1rem)] font-extrabold leading-[0.96] tracking-[-0.06em] text-brand-primary">Что обычно уточняют до начала работы</h2></div><div className="border-t border-brand-border">{faq.map(([question, answer], index) => <div key={question} className="border-b border-brand-border"><button type="button" className="flex w-full items-center justify-between gap-6 py-5 text-left text-lg font-bold tracking-[-0.04em] text-brand-primary sm:py-6 sm:text-xl" aria-expanded={openFaq === index} onClick={() => setOpenFaq(openFaq === index ? null : index)}><span>{question}</span><span className="shrink-0 text-2xl font-normal text-brand-accent" aria-hidden="true">{openFaq === index ? '−' : '+'}</span></button>{openFaq === index && <p className="max-w-2xl pb-6 text-base leading-7 text-[var(--color-text-secondary-content)] sm:text-lg">{answer}</p>}</div>)}</div></div></section>
    <section id="geography" className="bg-brand-surface" aria-labelledby="geography-title"><div className="content-container section-spacing grid gap-10 lg:grid-cols-[minmax(0,0.8fr)_minmax(16rem,0.7fr)] lg:items-end lg:gap-20"><div><p className="text-xs font-extrabold tracking-[0.12em] text-brand-secondary">ГЕОГРАФИЯ</p><h2 id="geography-title" className="mt-4 text-[clamp(2.3rem,4.4vw,4.25rem)] font-extrabold leading-[0.96] tracking-[-0.06em] text-brand-primary">Перевозим по России</h2><p className="mt-6 max-w-xl text-lg leading-relaxed text-[var(--color-text-secondary-content)]">Работаем как с регулярными направлениями, так и с разовыми маршрутами.</p></div><div className="w-full min-w-0 max-w-full border-l-2 border-brand-accent pl-6 sm:pl-8"><p className="text-sm font-extrabold tracking-[0.12em] text-brand-secondary">МАРШРУТЫ ПОД ЗАДАЧУ</p><div className="relative mt-7 h-32 w-full min-w-0 max-w-md" aria-label="Регулярные и разовые маршруты по России"><svg viewBox="0 0 400 128" className="absolute inset-0 h-full w-full" fill="none" aria-hidden="true"><path d="M34 83 C106 20, 180 26, 223 66 S315 104, 366 36" stroke="var(--color-graphite)" strokeWidth="1.25" /><path d="M34 83 C106 20, 180 26, 223 66" stroke="var(--color-accent-orange)" strokeWidth="1.25" /><circle cx="34" cy="83" r="5" fill="var(--color-accent-orange)" /><circle cx="223" cy="66" r="4" fill="var(--color-background)" stroke="var(--color-graphite)" strokeWidth="1.5" /><circle cx="366" cy="36" r="5" fill="var(--color-accent-orange)" /></svg><span className="absolute bottom-0 left-0 max-w-24 text-xs leading-4 text-[var(--color-text-secondary-content)]">регулярные маршруты</span><span className="absolute bottom-3 left-[49%] max-w-24 text-xs leading-4 text-[var(--color-text-secondary-content)]">направления под задачу</span><span className="absolute right-0 top-0 max-w-24 text-right text-xs leading-4 text-[var(--color-text-secondary-content)]">разовые перевозки</span></div></div></div></section>
    <section id="client-contact" className="bg-brand-background" aria-labelledby="contact-title"><div className="content-container section-spacing grid gap-14 lg:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)] lg:gap-20"><div><p className="text-xs font-extrabold tracking-[0.12em] text-brand-accent">НАЧАТЬ РАБОТУ</p><h2 id="contact-title" className="mt-4 max-w-xl text-[clamp(2.4rem,4.6vw,4.8rem)] font-extrabold leading-[0.96] tracking-[-0.06em] text-brand-primary">Есть маршрут или задача? Обсудим условия.</h2><p className="mt-7 max-w-md text-lg leading-relaxed text-[var(--color-text-secondary-content)]">Опишите перевозку в нескольких словах — уточним детали и предложим рабочий вариант.</p></div><div className="border-t-2 border-brand-accent pt-7 lg:pt-9"><DeliveryRequestForm variant="inline" /></div></div></section>
  </main>
}
