import type { Metadata } from 'next'
import './globals.css'
import TopMenu from './topMenu'
import Footer from './footer'
import { LayoutProvider } from './LayoutContext';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className='dark:bg-black dark:text-white font-montserrat'>
				<LayoutProvider>
				<div className='z-50'>
						<TopMenu />
				</div>
				<div className='pt-32 z-0'>
						{children}
				</div>
				</LayoutProvider>
				<div className='mb-0 z-50'>
					<Footer/>
				</div>
			</body>
    </html>
	)
}
