import type { Metadata } from 'next'
import './globals.css'
import TopMenu from './topMenu'
import Footer from './footer'
import { LayoutProvider } from './LayoutContext';


export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className="relative bg-[url('/MainBG.jpg')] bg-cover bg-center bg-fixed ">
				<div className="absolute inset-0 bg-[url('/MainBG.jpg')] bg-cover bg-center bg-fixed blur-md z-[-1]" />

				<div className="absolute inset-0 bg-white/25 dark:bg-black/40  z-0"></div> {/* Затемняющий слой */}
				<LayoutProvider>
					<div className="relative z-20">
						<TopMenu />
					</div>
					<div className="relative z-0">{children}</div>
					<div className="relative z-0">
						<Footer />
					</div>
				</LayoutProvider>
			</body>

		</html>
	);
}

